[package]
name = "cuda_dnn"
version = "0.1.0"
authors = ["Peter Jin <peterhaijin@gmail.com>"]
license = "BSD-2-Clause"
description = "cuDNN API bindings."
repository = "https://github.com/peterhj/libcuda_dnn"
keywords = ["cuda", "cudnn"]

#[features]
#default = []
#v3 = []
#v4 = []
#v5 = []

[lib]
name = "cuda_dnn"
path = "src/lib.rs"

[dependencies]
libc = "^0.2"
cuda = "^0.1"
float = "^0.1"
